"""Plotting and animation primitives for astronomical imaging simulations.

eyepiece provides a small set of pure functions for rendering, comparing,
and animating simulated images (point spread functions, coronagraph
detection maps, complex optical fields, and the like). Every public name
lives at the top level of this package; the submodules that implement them
(``images``, ``layout``, ``output``, ``anim``, ``scene``, ``stats``,
``_schematic``, ``_phasor``, ``insets``, ``profiles``, ``emphasis``) are
internal organization and are not part of the public API. The vocabularies a
caller reads against are exported alongside the functions: ``ARTIST_KEYS``,
the key set a result's ``artists`` dict draws from; ``PRESETS``, the
measured fps/dpi pairs for the usual animation destinations; and ``GLYPHS``,
the optical-element names ``rail`` draws.

Example::

    import eyepiece as ep

    result = ep.imshow_log(image)
    ep.save_fig(result.fig, "psf")

The library never imports a simulation library and never mutates
matplotlib's global state at import time; style is applied explicitly by
the caller (see ``eyepiece._style``), not captured when this package loads.

Every name below loads lazily on first access (PEP 562): ``import eyepiece``
alone never imports matplotlib, and ``import eyepiece.prepared`` -- the pure
numerical view records in the ``prepared`` submodule -- never does either.
Matplotlib and any renderer only load once a caller actually touches a name
that needs them.
"""

import importlib
import importlib.util

from eyepiece._version import __version__

__all__ = [
    "ARTIST_KEYS",
    "GLYPHS",
    "PRESETS",
    "Animation",
    "Frame",
    "MosaicResult",
    "PlotResult",
    "SourceStyles",
    "__version__",
    "animate",
    "blend",
    "bracket",
    "capture",
    "compare_grid",
    "compare_row",
    "convergence",
    "corner",
    "corner_overlay",
    "cov_ellipse",
    "curve_insets",
    "display_limits",
    "extent_arcsec",
    "extent_au",
    "extent_lod",
    "extent_lod_from_pixels",
    "fade",
    "fading_track",
    "file_metadata",
    "hist_vs_pdf",
    "imshow_diverging",
    "imshow_log",
    "kymograph",
    "label_arcsec",
    "label_au",
    "label_lod",
    "overlay_circle",
    "overlay_line",
    "phase_ring",
    "phasor",
    "plot_contrast_curve",
    "plot_radial",
    "provenance_fields",
    "provenance_text",
    "radial_profile_plot",
    "rail",
    "rail_panels",
    "record",
    "ruler",
    "save_fig",
    "schematic",
    "show_field",
    "sky_fan",
    "stamp",
    "trail",
    "triptych",
]

# name -> (submodule, attribute). __version__ is bound eagerly above (cheap,
# generated by hatch-vcs); every other name resolves through __getattr__ so
# the heavy, matplotlib-importing submodules load only on first use.
_LAZY_EXPORTS = {
    "ARTIST_KEYS": ("eyepiece._result", "ARTIST_KEYS"),
    "MosaicResult": ("eyepiece._result", "MosaicResult"),
    "PlotResult": ("eyepiece._result", "PlotResult"),
    "PRESETS": ("eyepiece.anim", "PRESETS"),
    "Animation": ("eyepiece.anim", "Animation"),
    "animate": ("eyepiece.anim", "animate"),
    "record": ("eyepiece.anim", "record"),
    "blend": ("eyepiece.emphasis", "blend"),
    "capture": ("eyepiece.emphasis", "capture"),
    "fade": ("eyepiece.emphasis", "fade"),
    "compare_grid": ("eyepiece.images", "compare_grid"),
    "compare_row": ("eyepiece.images", "compare_row"),
    "display_limits": ("eyepiece.images", "display_limits"),
    "imshow_diverging": ("eyepiece.images", "imshow_diverging"),
    "imshow_log": ("eyepiece.images", "imshow_log"),
    "kymograph": ("eyepiece.images", "kymograph"),
    "bracket": ("eyepiece.images", "bracket"),
    "overlay_circle": ("eyepiece.images", "overlay_circle"),
    "overlay_line": ("eyepiece.images", "overlay_line"),
    "ruler": ("eyepiece.images", "ruler"),
    "show_field": ("eyepiece.images", "show_field"),
    "triptych": ("eyepiece.images", "triptych"),
    "Frame": ("eyepiece.layout", "Frame"),
    "SourceStyles": ("eyepiece.layout", "SourceStyles"),
    "extent_arcsec": ("eyepiece.layout", "extent_arcsec"),
    "extent_au": ("eyepiece.layout", "extent_au"),
    "extent_lod": ("eyepiece.layout", "extent_lod"),
    "extent_lod_from_pixels": ("eyepiece.layout", "extent_lod_from_pixels"),
    "label_arcsec": ("eyepiece.layout", "label_arcsec"),
    "label_au": ("eyepiece.layout", "label_au"),
    "label_lod": ("eyepiece.layout", "label_lod"),
    "save_fig": ("eyepiece.output", "save_fig"),
    "plot_contrast_curve": ("eyepiece.profiles", "plot_contrast_curve"),
    "plot_radial": ("eyepiece.profiles", "plot_radial"),
    "radial_profile_plot": ("eyepiece.profiles", "radial_profile_plot"),
    "file_metadata": ("eyepiece.provenance", "file_metadata"),
    "provenance_fields": ("eyepiece.provenance", "provenance_fields"),
    "provenance_text": ("eyepiece.provenance", "provenance_text"),
    "stamp": ("eyepiece.provenance", "stamp"),
    "fading_track": ("eyepiece.scene", "fading_track"),
    "sky_fan": ("eyepiece.scene", "sky_fan"),
    "trail": ("eyepiece.scene", "trail"),
    "phasor": ("eyepiece._phasor", "phasor"),
    "phase_ring": ("eyepiece._phasor", "phase_ring"),
    "curve_insets": ("eyepiece.insets", "curve_insets"),
    "GLYPHS": ("eyepiece._schematic", "GLYPHS"),
    "rail": ("eyepiece._schematic", "rail"),
    "rail_panels": ("eyepiece._schematic", "rail_panels"),
    "schematic": ("eyepiece._schematic", "schematic"),
    "convergence": ("eyepiece.stats", "convergence"),
    "corner": ("eyepiece.stats", "corner"),
    "corner_overlay": ("eyepiece.stats", "corner_overlay"),
    "cov_ellipse": ("eyepiece.stats", "cov_ellipse"),
    "hist_vs_pdf": ("eyepiece.stats", "hist_vs_pdf"),
}


def __getattr__(name):
    """Resolve a public name on first access (PEP 562), then cache it.

    A name that is not an export but names a submodule (``eyepiece._style``,
    ``eyepiece.mpl``) imports and returns that submodule, as plain attribute
    access did before the package loaded lazily. Only the requested
    submodule loads, so ``import eyepiece.prepared`` stays free of pyplot.
    """
    try:
        module_name, attr_name = _LAZY_EXPORTS[name]
    except KeyError:
        if not name.startswith("__") and importlib.util.find_spec(f"{__name__}.{name}"):
            return importlib.import_module(f"{__name__}.{name}")
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(importlib.import_module(module_name), attr_name)
    globals()[name] = value
    return value


def __dir__():
    """Report the public names, including those not yet lazily loaded."""
    return sorted(set(globals()) | set(_LAZY_EXPORTS))
